
### Path settings
path:
  expname: ble-rssi-exp1
  datadir: data/BLE/exp1/
  logdir: logs/BLE/


### rendering settings
render:
  mode: 'rssi'
  near: 0
  far: 1
  n_samples: 32
  scale_worldsize: 60  # 60m x 60m, normalize the coordinates to [0, 1]


### training settings
train:
  lr: 1e-3
  weight_decay: 5e-5
  T_max: 10000
  eta_min: 1e-6
  batch_size: 128
  total_iterations: 10000
  load_ckpt: True

  save_freq: 100
  val_freq: 2500
  report_freq: 100


### network settings
networks:
  D: 8
  W: 256
  skips: [4]
  is_embeded: True
  multires_pts: 10
  multires_view: 10
  multires_tx: 10

